### ISSUE TITLE
The Server Side example is out of date

### ISSUE THREAD

**Issue by semiautomatix** [solidjs-community/mediakit#33]
Hey, thanks for the great project. I was poking around hoping to find a better solution to my issue regarding reading the session on the server side. I've noted your example is out of date, as `createServerData$` is now no longer used. 

It seems the request or data from the session must be passed down on each function call, rather than accessing the session directly, as per the Vinxi `useSession`.

**Comment by HokkaidoInu** [comment]
It appears that the example on this link https://mediakit-taupe.vercel.app/auth/getsession (which is referenced at the bottom of the README.md) is updated but not in the README.md
I am also trying to get the session on the server side but when trying to use the example in the link I get "TypeError: Cannot read properties of undefined (reading 'id')", that may be due to something I'm not doing right on my end. If you could let me know if you also get the same error, that would be great.

**Comment by OrJDev** [comment]
https://github.com/solidjs-community/mediakit/commit/55a6c625c6dc266c7bbbb0d70a9a81a84606e885

i think that is it, follow create-jd-app usage for the best solid auth usage.
